#!/bin/bash
. tablemeta
. ch
function insert()
{

	if [ $1 == "first" ]
	then 
			
		while true 
			do
					echo -e "Please Enter The Name of Table \c"
					read tableName
					valid $tableName
					res=$?
					if [ $res == 2 ]
					then 
					break
					fi
					echo "correct input enter agin"
			done
			
	fi

	
	Meta="Meta"
	tableNameMeta="$tableName$Meta"
    if [ -s $tableNameMeta ]
    then
	  . ../searchExitfile $tableName
	  result=$?
	  if [ $result == 0 ]
	  then 
	  echo "Table $tableName Not Exist"
	  tableMenu
	  else
		read -r firstline< ./$tableNameMeta
		firstline=$(($firstline+1))
		lines=$(awk  'END{print NR}' $tableNameMeta)
		lines=$(($lines-1))
		table_line=$(awk  'END{print NR}' $tableName)
		if [ $table_line -ne 0 ]
		then
		echo  "" >> $tableName
		table_line=$(($table_line+1))
		echo -n  $table_line>> $tableName
                 echo -n ":">> $tableName
		else
		table_line=1
		echo -n  $table_line>>  $tableName
		 echo -n ":">> $tableName
		fi
		
		for((i=2;i<=$firstline;i++))
		do
			
			type=` awk -F: 'NR=='$i' {print  $2 }' $tableNameMeta `
			while true
			do
				awk -F: 'NR=='$i' {print "enter the value of " $1 " which is " $2 }' $tableNameMeta
				read value
				valid $value
				res=$?
				if [  $type == "int" ]
				then
					if [ $res == 1 ]
					then
						  echo -n  $value>> $tableName
						break;
					else 
						echo "the type must be integer"
					fi
				fi

				if [  $type == "string" ]
				then
					if [ $res == 2 ]
					then
						  echo -n  $value>> $tableName
						break;
					else 
						echo "the type must be string"
					fi
				fi		




			done
	        if [ $i -ne  $firstline  ]
	        then
	        echo -n ":">> $tableName
	        fi
		done
		tableMenu
        fi
	else
	echo  " empty"
	tableMeta $tableName
	fi
	insert "second"
}