#!/bin/bash
. ./selectall
. ./selectcol
function selectMenu 
{
  echo -e "****************Select Menu**********************"
  echo "* 1. Select All Columns of a Table              *"
  echo "* 2. Select Specific Column from a Table        *"
  echo "* 3. Back To Tables Menu                        *"
  echo "* 4. Back To starting Menu                      *"
  echo "* 5. Exit                                       *"
  echo "*************************************************"
  echo -e "Please Enter Your Choice: \c"
  read choice
  case $choice in
    1) selectAllCols ;;
    2) selectCol ;;
    3) clear; tableMenu ;;
    4) clear; cd .. 2>>./.error.log; startingMenu ;;
    5) exit ;;
    *) echo " Wrong Choice " ; selectMenu;
  esac
}